### ISSUE TITLE
Database Error Connection refused

### ISSUE THREAD

**Issue by Txxicer** [imagegenius/docker-immich#13]
I get the following error

![image](https://user-images.githubusercontent.com/89355218/214143008-83326aea-8a59-4e2e-befc-d10953a5d326.png)

The console says the following:

immich    | [Nest] 142  - 01/23/2023, 9:25:32 PM   ERROR [TypeOrmModule] Unable                                                                                                                                                              to connect to the database. Retrying (1)...
immich    | Error: Connection terminated due to connection timeout
immich    |     at Connection.<anonymous> (/app/immich/server/node_modules/pg/li                                                                                                                                                             b/client.js:132:73)
immich    |     at Object.onceWrapper (node:events:627:28)
immich    |     at Connection.emit (node:events:513:28)
immich    |     at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/co                                                                                                                                                             nnection.js:57:12)
immich    |     at Socket.emit (node:events:513:28)
immich    |     at TCP.<anonymous> (node:net:301:12)
immich    | [Nest] 147  - 01/23/2023, 9:25:45 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich    | Error: Connection terminated due to connection timeout
immich    |     at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
immich    |     at Object.onceWrapper (node:events:627:28)
immich    |     at Connection.emit (node:events:513:28)
immich    |     at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
immich    |     at Socket.emit (node:events:513:28)
immich    |     at TCP.<anonymous> (node:net:301:12)

**Comment by hydazz** [comment]
is the immich and postgres container on the same docker network? or are they able to communicate with each other?

**Comment by Txxicer** [comment]
I didnt changed anything according to networks, ports or database. It is in the same network on the same machine.

**Comment by hydazz** [comment]
can you paste the `docker run` command that pops up when you recreate the immich and postgres container please

**Comment by Txxicer** [comment]
How should I paste the command exactly? I normally use `docker-compose` command according to `docker-compose.yml`

**Comment by hydazz** [comment]
Oh sorry. Can you paste your docker compose for immich and postgres

**Comment by Txxicer** [comment]
Thats the compose:

```
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
   #   - PUID=1000
   #   - PGID=1000
      - DB_HOSTNAME=192.168.1.10
      - DB_PORT=5432
      - DB_DATABASE_NAME=databasename
      - DB_USERNAME=postgresql_username
      - DB_PASSWORD=postgresql_password
      - REDIS_HOSTNAME=192.168.1.10
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password #optional
      - JWT_SECRET=Is06dXSJ2vzTob6n9R0PJoLyoZ1pBIqb8pL6yJo6MyQVSi1mJ1pmx5h29jS2forTcEkSaGK72kZ1UO6S3FeWATwprOlRziKsP7gsw3JVK3JmePmkctd8ptdrV1ZDb4D4
      # signature: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzM3MDg5MzgsImV4cCI6bnVsbCwiYXVkIjoiZnJlc2h5c25hcy5kZSIsInN1YiI6ImZyZWRkeS5mLjFAd2ViLmRlIn0.qznI34NzBoBEnvVqubgUXujsveCLGg_qf3zMqTwvMi4
      - DISABLE_MACHINE_LEARNING=false #optional
      - TZ=Europe/Berlin #optional
    volumes:
      - /volume1/docker/Immich/config:/config
      - /volume1/Freddy_SSD/Sicherer_Ordner:/photos
    ports:
      - 56905:8080
    restart: unless-stopped
```version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
   #   - PUID=1000
   #   - PGID=1000
      - DB_HOSTNAME=192.168.1.10
      - DB_PORT=5432
      - DB_DATABASE_NAME=databasename
      - DB_USERNAME=postgresql_username
      - DB_PASSWORD=postgresql_password
      - REDIS_HOSTNAME=192.168.1.10
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password #optional
      - JWT_SECRET=Is06dXSJ2vzTob6n9R0PJoLyoZ1pBIqb8pL6yJo6MyQVSi1mJ1pmx5h29jS2forTcEkSaGK72kZ1UO6S3FeWATwprOlRziKsP7gsw3JVK3JmePmkctd8ptdrV1ZDb4D4
      # signature: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzM3MDg5MzgsImV4cCI6bnVsbCwiYXVkIjoiZnJlc2h5c25hcy5kZSIsInN1YiI6ImZyZWRkeS5mLjFAd2ViLmRlIn0.qznI34NzBoBEnvVqubgUXujsveCLGg_qf3zMqTwvMi4
      - DISABLE_MACHINE_LEARNING=false #optional
      - TZ=Europe/Berlin #optional
    volumes:
      - /volume1/docker/Immich/config:/config
      - /volume1/Freddy_SSD/Sicherer_Ordner:/photos
    ports:
      - 56905:8080
    restart: unless-stopped

Was there the same problem in #12 ?

**Comment by hydazz** [comment]
can you remove the `REDIS_PASSWORD` variable unless your redis password is actually `password`.
Update the image to the latest version, make sure that the postgres login variables are correct, lmk how you go

**Comment by hydazz** [comment]
btw for context: the screenshot shows that it cant connect to the `server` service because the `server` service is failing to start as it cant communicate with postgres

**Comment by Txxicer** [comment]
Hi,

Just to be clear, do I need to setup an extra postgres server? I think the docker image does this self?

**Comment by spiffzilla** [comment]
I get the same error. If it helps, this is what the log says:
Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted

**Comment by hydazz** [comment]
@Txxicer 
> Hi,
> 
> Just to be clear, do I need to setup an extra postgres server? I think the docker image does this self?

This does require an external postgres 14 container/service

**Comment by hydazz** [comment]
@spiffzilla can you post your immich template

**Comment by spiffzilla** [comment]
@hydazz 

`<?xml version="1.0"?>
<Container version="2">
  <Name>Immich</Name>
  <Repository>ghcr.io/imagegenius/immich:noml</Repository>
  <Registry>https://hub.docker.com/r/imagegenius/immich</Registry>
  <Network>bridge</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://github.com/imagegenius/docker-immich</Support>
  <Project>https://documentation.immich.app/</Project>
  <Overview>Self-hosted photo and video backup solution with high performance.&#xD;
Note that this is a community-made "all-in-one" container for Immich for convenience. &#xD;
It does still require a PostgreSQL 14 databse and Redis to be setup! &#xD;
 &#xD;
For an advanced setup, but official release, see here for how to setup Immich with Docker Compse on unRAID: https://documentation.immich.app/docs/install/unraid &#xD;
  &#xD;
Post-Install Instructions: https://documentation.immich.app/docs/install/post-install&#xD;
 &#xD;
NOTE: If your CPU does not support AVX for machine-learning, please use the :noml tag instead of :latest so machine-learning can be stripped out and still allow Immich to run for you! &#xD;
 &#xD;
Please force an update of the container in order to pull the latest Immich updates automatically.</Overview>
  <Category>Backup: Cloud: MediaApp:Photos</Category>
  <WebUI>http://[IP]:[PORT:8080]</WebUI>
  <TemplateURL>https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/immich.xml</TemplateURL>
  <Icon>https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/icons/immich.png</Icon>
  <ExtraParams/>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1674843829</DateInstalled>
  <DonateText>Donate</DonateText>
  <DonateLink>http://paypal.me/corneliousjd</DonateLink>
  <Requires>PostgreSQL 14, Redis</Requires>
  <Config Name="Web Interface" Target="8080" Default="2283" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">2283</Config>
  <Config Name="AppData" Target="/config" Default="/mnt/user/appdata/Immich" Mode="rw" Description="Contains the logs." Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/Immich</Config>
  <Config Name="Photos Share" Target="/photos" Default="/mnt/user/photos" Mode="rw" Description="Contains all media uploaded to Immich." Type="Path" Display="always" Required="true" Mask="false">/mnt/user/media/bilder/immich/</Config>
  <Config Name="Timezone" Target="TZ" Default="America/Detroit" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">Europe/Stockholm</Config>
  <Config Name="Database Host" Target="DB_HOSTNAME" Default="192.168.1.10" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">xxxxxxxxxxxx</Config>
  <Config Name="Database Port" Target="DB_PORT" Default="5432" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">5432</Config>
  <Config Name="Database Name" Target="DB_DATABASE_NAME" Default="immich" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">immich</Config>
  <Config Name="Database Username" Target="DB_USERNAME" Default="postgres" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">postgres</Config>
  <Config Name="Database Password" Target="DB_PASSWORD" Default="postgres" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="true">xxxxxxxxxxxx</Config>
  <Config Name="Redis Host" Target="REDIS_HOSTNAME" Default="xxxxxxxxxxxx" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">xxxxxxxxxxxx</Config>
  <Config Name="Redis Port" Target="REDIS_PORT" Default="6379" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">6379</Config>
  <Config Name="JWT Secret" Target="JWT_SECRET" Default="somelongrandomstring" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">thereisnogravity</Config>
  <Config Name="PUID" Target="PUID" Default="1000" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">1000</Config>
  <Config Name="PGID" Target="PGID" Default="1000" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">1000</Config>
</Container>
`

**Comment by Txxicer** [comment]
Thanks everyone for help.

I tried to fix it now, took about 2 hours.

I had to setup a postgreSQL server and a redis server, both with a gui interface.

Then I entered the datas from the databases into the docker-compose.yml from immich. Now it works.
I thought I was easier because I'm used to images managing databases themselves.

But what I dont understand, why does redis doesnt have a username or password?

**Comment by hydazz** [comment]
@Txxicer Did you look at https://github.com/imagegenius/docker-immich#unraid-migrate-from-docker-compose?

**Comment by hydazz** [comment]
@spiffzilla try using the redis docker-mod, https://github.com/imagegenius/docker-immich#redis-1,

if there are any errors look in `docker logs Immich` and post them here

**Comment by Txxicer** [comment]
> Did you look at https://github.com/imagegenius/docker-immich#unraid-migrate-from-docker-compose?

I looked at it, but it uses unraid right? And isnt it possible to use it in docker? Do without an extra system?
Any may you have a template for the required .env file?

**Comment by hydazz** [comment]
> I looked at it, but it uses unraid right?

it does say unraid but its the same setup as any host that used docker-compose (just some paths need changing)

> Any may you have a template for the required .env file?

what does this mean? if you originally installed using https://immich.app/docs/install/docker-compose then you would have the .env

**Comment by Txxicer** [comment]
No, I installed immich with your image. And yes, there is now .env as you said.

But how should I migrate a already existing folder structure into your image?

I currently have the following setup in volumes for my photos (example):

```
    volumes:
      - /volume1/docker/Immich/config:/config
      - /volume1/myphotos:/photos:/photos
```

And in `/volume1/myphotos` are my photos saved. But they arent shown in immich.

Should I specify a `UPLOAD_LOCATION` variable in environment?

**Comment by hydazz** [comment]
@Txxicer, I thought you meant you wanted to migrate but you are setting this up from scratch?

if so discard everything I've said previously.

You must upload images to immich, you cant just point the folder to it.

You can follow these steps to properly upload images to immich

edit your docker-compose volumes to look like this:
```yaml
    volumes:
      - /volume1/docker/Immich/config:/config
      - /volume1/myphotos:/uploads
      - /volume1/photos:/photos
```

Open the immich webui, log in, go to `/user-settings` in the URL, and make a new API key (keep it noted)

open a shell into the immich container and run `npm i -g immich`

then run `immich upload --key <api_key> --server http://<ip>:<port>/api -d /uploads`

this will upload the contents of `/volume1/myphotos` to `/volume1/photos` on the host, and they will also be properly added to immich

**Comment by Txxicer** [comment]
May it was my fault, I thoght migrating means migrate existing folder structure / media to a new immich server haha.

Buy yes, I also found this rn, its the CLI https://github.com/immich-app/CLI

And with this works.

Pictures are uploading now.

Thanks! :)

**Comment by spiffzilla** [comment]
@hydazz 

Tried the docker_mods (didn't solve the problem) and here are the logs

Btw. What i'm using is Unraid with Immich docker, Redis docker and Postgresql14 docker

`docker logs Immich
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying imagegenius/mods:universal-redis files to container
[mod-init] imagegenius/mods:universal-redis applied to container
[migrations] started
[migrations] no migrations found

-------------------------------------
|        __  _____ _____       __   |
|       / / |_   _/ ____|     / /   |
|      / /    | || |  __     / /    |
|     / /     | || | |_ |   / /     |
|    / /     _| || |__| |  / /      |
|   /_/     |_____\_____| /_/       |
-------------------------------------
To support the app dev(s) visit:
Immich: https://www.buymeacoffee.com/altran1502
-------------------------------------
User/Group ID
-------------------------------------
User UID: 1000
User GID: 1000
-------------------------------------
**** Adding redis to package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
fetch https://packages.imagegenius.io/v3.17/x86_64/APKINDEX.tar.gz
(1/1) Installing redis (7.0.8-r0)
Executing redis-7.0.8-r0.pre-install
Executing redis-7.0.8-r0.post-install
Executing busybox-1.35.0-r29.trigger
OK: 264 MiB in 153 packages
[custom-init] No custom files found, skipping...
[ig-init] done.
nginx: [warn] duplicate MIME type "text/html" in /defaults/nginx.conf:37
Listening on 0.0.0.0:3000
[Nest] 190  - 01/28/2023, 6:37:14 PM    WARN The current JWT_SECRET key is insecure. It should be at least 128 bits long!
[Nest] 190  - 01/28/2023, 6:37:14 PM    WARN Here is a new, securely generated key that you can use instead: hHFRvU2w0a4U9g9+/uNvdS1FQEqZpR6LUER67S3hEho=
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [NestFactory] Starting Nest application... +116ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +51ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] DownloadModule dependencies initialized +1ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +10ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:14 PM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +0ms
[Nest] 202  - 01/28/2023, 6:37:15 PM    WARN The current JWT_SECRET key is insecure. It should be at least 128 bits long!
[Nest] 202  - 01/28/2023, 6:37:15 PM    WARN Here is a new, securely generated key that you can use instead: qkshV6xvmNVf6rxrrxGEraGIuDCwi51gKEjB7uX3KGw=
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [NestFactory] Starting Nest application... +53ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +24ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +5ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 202  - 01/28/2023, 6:37:15 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 190  - 01/28/2023, 6:37:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
[Nest] 202  - 01/28/2023, 6:37:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
[Nest] 190  - 01/28/2023, 6:37:37 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
[Nest] 202  - 01/28/2023, 6:37:38 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
[Nest] 190  - 01/28/2023, 6:37:50 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/app/immich/server/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:627:28)
    at Connection.emit (node:events:513:28)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12)
`

**Comment by spiffzilla** [comment]
I reinstalled everythin, redis, posgresql14, immich

Now i get these in my postgre log

2023-01-28 22:54:55.327 CET [121] FATAL:  database "immich" does not exist
2023-01-28 22:54:56.857 CET [123] FATAL:  database "immich" does not exist
2023-01-28 22:54:58.348 CET [124] FATAL:  database "immich" does not exist
2023-01-28 22:54:59.878 CET [125] FATAL:  database "immich" does not exist
2023-01-28 22:55:01.370 CET [126] FATAL:  database "immich" does not exist

Looks like immich failed to create db structure?

And the immich log (partial) says this

[Nest] 151  - 01/28/2023, 10:53:46 PM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +0ms
[Nest] 151  - 01/28/2023, 10:53:46 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [NestFactory] Starting Nest application...
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +38ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +4ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 168  - 01/28/2023, 10:53:48 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 168  - 01/28/2023, 10:53:48 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[Nest] 151  - 01/28/2023, 10:53:49 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
error: database "immich" does not exist

**Comment by hydazz** [comment]
@spiffzilla 

>error: database "immich" does not exist

is `POSTGRES_DB` set to immich in the postgres template?

**Comment by spiffzilla** [comment]
> @spiffzilla
> > error: database "immich" does not exist
> is `POSTGRES_DB` set to immich in the postgres template?
Yes it was. I have removed all dockers and will do a complete reinstallation pretty soon.
Hopefully it will be ok then ;-)

**Comment by spiffzilla** [comment]
Quick update. 
Efter reinstalling everything with the new updated version of Immich everything started to work just fine.
