### ISSUE TITLE
intel iGPU machine learning acceleration

### ISSUE THREAD

**Issue by mich2k** [imagegenius/docker-immich#295]
Hello,
Wondering if it is possible to use this image with intel iGPU/LP iGPU for ML acceleration as described [here](https://immich.app/docs/features/ml-hardware-acceleration/)

I'm asking this since, to my understanding, the -e field only supports cuda

Thanks

ps: I'm running on unraid so is also a bit trick to configure the hwaccel.ml.yml

**Comment by martabal** [comment]
> ps: I'm running on unraid so is also a bit trick to configure the hwaccel.ml.yml

Did you install immich with the `docker-compose install` method or are you using this AIO image? I'm asking this because enabling GPU acceleration for machine learning with this image has nothing to do with `docker-compose` or `hwaccel.ml.yml` on unraid.

If you use this AIO image, currently only CUDA is supported for machine learning, there are issues with openvino, you can follow the progress here #288

**Comment by mich2k** [comment]
I'm running this AIO image, and now I understood the issue here… I was talking about OpenVINO indeed, ML acceleration is only possible with immich on baremetal then..

Furthermore, I was not updated about the python version requirements and thought was already possible, is a true pity because cpus really struggle with thousands of medias to process

Will follow the issue and hope for a resolution, to my understanding the worst case should be on april (ubuntu24 lts release date)

Thanks for tracking down this issue

**Comment by martabal** [comment]
Yeah that's something that I really want too. 

I created a custom Docker image that compiles Python 3.10 and installs onnxruntime-openvino, but even with that it didn't work. Some users running immich with the official machine learning image reported the same errors I had, hope everything gets better with `1.17`
