### ISSUE TITLE
All my photos are gone/theres an error in the logs saying migration failed

### ISSUE THREAD

**Issue by hydazz** [imagegenius/docker-immich#64]
https://github.com/imagegenius/docker-immich/pull/47 was recently merged to the `main` branch, so when you upgrade the container, it would have attempted to modify the database, and replace the file paths from `upload/...` to `/photos/...`. In theory, this should not fail, but there might be issues we have not accounted for, like if you're using postgres docker mod, it will fail, try running `python3 /defaults/migrate.py` after you restart the container.

**If there's still an error**, whether or not your using the Postgres docker mod, comment the error below and we'll try to get it resolved ASAP.

**Comment by Medic97** [comment]
(Full log can be downloaded [here](https://drive.google.com/file/d/1pRD89Ljqg6LPD_L9dOjch06e4WLoRiBn/view?usp=share_link))
I just updated the container and received this error and much more. On first boot I got this error, running "python3 /defaults/migrate.py" in the container after restart gave me the same error, unable to connect.

I then restarted and got this error 
`E: Package 'redis-server' has no installation candidate
chown: invalid user: ‘postgres:postgres’
PostgreSQL Database Already Initialised
[custom-init] No custom files found, skipping...
s6-envuidgid: fatal: unknown user: postgres
s6-rc: warning: unable to start service svc-mod-universal-postgres: command exited 1
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory`

it tried to start the app and got this error
`[Nest] 390  - 04/16/2023, 11:17:18 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory`

I restarted the container it finally seemed to run the update and while starting i got this error.
`[Nest] 1856  - 04/16/2023, 11:20:56 AM     LOG [SearchService] Running bootstrap
Request #1681658456700: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"`
`/app/immich/server/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23
        var _this = _super.call(this, message) || this;
                           ^
ServerError: Request failed with HTTP code 503 | Server said: Not Ready or Lagging
    at ServerError.TypesenseError [as constructor] (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/TypesenseError.js:23:28)
    at new ServerError (/app/immich/server/node_modules/typesense/lib/Typesense/Errors/ServerError.js:25:42)
    at ApiCall.customErrorForResponse (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:347:21)
    at /app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:204:58
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:33:23)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at step (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:18:139)
    at Object.next (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:14:53)
    at fulfilled (/app/immich/server/node_modules/typesense/lib/Typesense/ApiCall.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  httpStatus: 503
}`

Then on shutdown I get this error.
`023-04-16 11:25:15.748 EDT [2007] LOG:  received fast shutdown request
[2023-04-16 11:25:15 -0400] [2174] [INFO] Handling signal: term
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
waiting for server to shut down....2023-04-16 11:25:15.880 EDT [2007] LOG:  aborting any active transactions
2023-04-16 11:25:15.884 EDT [2007] LOG:  background worker "logical replication launcher" (PID 2038) exited with exit code 1
2023-04-16 11:25:15.885 EDT [2033] LOG:  shutting down
missing 'error' handler on this Redis client`

My pictures seem to be intact, haven't tried uploading or running any jobs yet.

**Comment by hydazz** [comment]
all these errors descend from apt failing to install Redis:

```
Err:7 http://archive.ubuntu.com/ubuntu jammy/universe Sources
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:21965520 [weak]
   - SHA256:86f7de9edf4dd4fcb1244b68a3f09c08a16032b0d81b732551d17926205db572
   - SHA1:4de6ed18c0290ae2c1144683240dc2ec17cf07a6 [weak]
   - MD5Sum:7890c4c325e6c23987fcc5f776b78a84 [weak]
  Hashes of received file:
   - SHA256:3d5c57b3d1d870155a25db4a2b9782e0fa4e512eeeab8e93092c9700649aaba7
   - SHA1:4af28456c95a3e9f64699300fe5836b9fc2c388a [weak]
   - MD5Sum:0a5bb5dd640e4c80565f33eb302b3147 [weak]
   - Filesize:21965520 [weak]
  Last modification reported: Thu, 21 Apr 2022 16:16:02 +0000
  Release file created at: Thu, 21 Apr 2022 17:16:08 +0000
```

have to tried recreating the container? does `apt update` succeed if executed in the container?

**Comment by Medic97** [comment]
After posting I did manage to run python3 /defaults/migrate.py and it succeeded but didn't change the errors.
I just recreated and same errors. 
ran apt update, found 5 upgradable, upgraded them, restarted and still having same issue.

**Comment by hydazz** [comment]
can you recreate the container and post the full output of `docker logs` once the container has fully started

**Comment by hydazz** [comment]
try downgrading to `ghcr.io/imagegenius/immich:v1.53.0-ig84`, any success?

**Comment by Medic97** [comment]
Sam results, restarted my nas in between and also went to 83. All doing the exact same thing.

**Comment by hydazz** [comment]
do the `missing 'error' handler on this Redis client` persist if you try using an external redis server?

**Comment by Medic97** [comment]
I dont have one, I was using the all in one since this was the second container I set up and didn't want to mess with connecting different containers.

**Comment by hydazz** [comment]
What is your system? like a synology? do you use docker-compose or `docker run` or something else? can you provide us with either or?

**Comment by Medic97** [comment]
On a qnap using container station and I guess I use docker compose.

I updated to the latest one and while it still errors out, it's a more detailed error.
This one on startup.
`2023-04-18 19:42:32 -0400] [607] [INFO] Booting worker with pid: 607
[Nest] 561  - 04/18/2023, 7:42:54 PM   ERROR [RedisIoAdapter] Redis pubClient: Error: connect ETIMEDOUT`
This one on shutdown.
`[2023-04-18 16:38:43 -0400] [2183] [INFO] Handling signal: term
[Nest] 1877  - 04/18/2023, 4:38:43 PM   ERROR [RedisIoAdapter] Redis pubClient: Error: connect ECONNREFUSED 127.0.0.1:6379`

The code im using to create the container.
`version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1004
      - PGID=100
      - TZ=America/New_York
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=uuNQVlew7MzjCp1i5cMfr7QVDs78cEKWthJi1CGl8x9DQh++7cxVe/TOHPFPrTqO6VB3RQSrQO+AvgUZM517pz12/pj6iSS4NmIoz0as+GMe+CuvhVnnyLYkNr6U6733JdGh+IzQ266uc4RQolp9h1g9htcj1H9QzzB4P2LyCuM= 
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres #set Docker mods for both Redis and PostgreSQL
    volumes:
      - /share/CACHEDEV1_DATA/Container/Docker Data/Immich:/config
      - /share/CACHEDEV3_DATA/NAS Pics/Immich/Photos:/photos
    ports:
      - 8080:8080
    network_mode: host
    restart: always`

**Comment by hydazz** [comment]
any change with `network_mode: host` set to `network_mode: bridge`?

**Comment by Medic97** [comment]
Made the change, same error.

**Comment by hydazz** [comment]
🤔 very very odd, it worked before you updated? then you attempted to downgrade to the version before the update, which should rule out that the upgrade broke anything haha

perhaps try setting `image: ghcr.io/imagegenius/immich:latest` to `image: ghcr.io/imagegenius/immich:noml` - to see if the error persists with a completely different base
